import { FieldValue } from '@colanode/core';

/**
 * The field types an agent can both create on a database and write values for.
 * `file`, `relation`, `rollup` and the audit fields (created_at/by, updated_at/by)
 * are deliberately excluded: they have no agent-writable field value.
 */
export type AgentFieldType =
  | 'boolean'
  | 'email'
  | 'multi_select'
  | 'number'
  | 'phone'
  | 'select'
  | 'text'
  | 'url';

/** A logical field the caller wants; ids are generated by the builder. */
export type AgentFieldSpec = {
  name: string;
  type: AgentFieldType;
  /** Option names, for `select` / `multi_select` only. */
  options?: string[];
};

export const SELECT_OPTION_COLORS = [
  'gray',
  'orange',
  'yellow',
  'green',
  'blue',
  'purple',
  'pink',
  'red',
] as const;

export const selectOptionColor = (index: number): string =>
  SELECT_OPTION_COLORS[index % SELECT_OPTION_COLORS.length]!;

/**
 * Map a logical value onto the Colanode `FieldValue` union. `select` and
 * `multi_select` values are option ids, not option names.
 */
export const toFieldValue = (
  type: AgentFieldType,
  value: unknown
): FieldValue => {
  switch (type) {
    case 'boolean':
      if (typeof value !== 'boolean') {
        throw new Error(`Field of type ${type} expects a boolean value`);
      }
      return { type: 'boolean', value };
    case 'number':
      if (typeof value !== 'number' || Number.isNaN(value)) {
        throw new Error(`Field of type ${type} expects a number value`);
      }
      return { type: 'number', value };
    case 'text':
      if (typeof value !== 'string') {
        throw new Error(`Field of type ${type} expects a string value`);
      }
      return { type: 'text', value };
    case 'email':
    case 'phone':
    case 'select':
    case 'url':
      if (typeof value !== 'string') {
        throw new Error(`Field of type ${type} expects a string value`);
      }
      return { type: 'string', value };
    case 'multi_select':
      if (
        !Array.isArray(value) ||
        value.some((item) => typeof item !== 'string')
      ) {
        throw new Error(`Field of type ${type} expects an array of option ids`);
      }
      return { type: 'string_array', value: value as string[] };
  }
};
